In [1]:
import numpy as np

In [4]:
list_ = [ 1 , 2 , 3 , 4 , 5 ]

In [5]:
list_

[1, 2, 3, 4, 5]

In [7]:
array_list = np.array(object = list_)

In [ ]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.



In [1]:
#There is a difference in the data types of the variables list_ and array_list. The variable list_ is a Python list, which can contain elements of different data types,
# while array_list is a NumPy array, which typically has a homogeneous data type for all its elements.

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [ ]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of elements in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
# Q3 Considering the following changes in the variable, array_list:

# array_list = np.array(object = list_, dtype = int)

#Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and
#every element present in both the variables, list_ and arra_list. 

In [4]:
array_list = np.array(object = list_, dtype = int)

In [5]:
array_list

array([1, 2, 3, 4, 5])

In [6]:
# Print data types of elements in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
Q4  Write a code to find the following characteristics of variable, num_array:

# (i)	 shape

# (ii) size

In [7]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find the shape of num_array
shape = num_array.shape
print("Shape of num_array:", shape)

# Find the size of num_array
size = num_array.size
print("Size of num_array:", size)

Shape of num_array: (2, 3)
Size of num_array: 6


In [ ]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [9]:
zero_array = np.zeros((3, 3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?

# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [11]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
